services:
  - type: web
    name: vitravel-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: ML_SERVICE_URL
        sync: false
